=== alexander5525/stock/StockSim/0.95-0.975/config.dtd
<!ELEMENT config (settings)*>
<!ELEMENT settings (setting | list)*>
<!ELEMENT setting EMPTY>
<!ELEMENT list (item | group)+>
<!ELEMENT group (item)+>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
    switchcode CDATA #IMPLIED
>
<!ATTLIST group
    name CDATA #REQUIRED
>
<!ATTLIST setting
    name CDATA #REQUIRED
    boolean (true | false) #IMPLIED
    value CDATA #IMPLIED
>
<!ATTLIST settings
    name CDATA #REQUIRED>

=== alexander5525/stock/StockSim/0.95-0.975/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config><settings name="preferences"><setting name="Calculate strategies on all available data" boolean="true" /><setting name="Recalculate strategies after editing conditions" boolean="true" /><setting name="Calculate strategies on live data" boolean="true" /><setting name="Ask to name variables" boolean="false" /><setting name="When debugging skip to next marked stock" boolean="true" /><setting name="Show group items in suggestions" boolean="true" /></settings><settings name="common stocks"><list><group name="INDICES"><item switchcode="HANG SENG">^HSI</item><item switchcode="CAC">^FCHI</item><item switchcode="TECDAX">^TECDAX</item><item switchcode="FTSE">^FTSE</item><item switchcode="NIKKEI">^N225</item><item switchcode="BITCOIN">BTC-USD</item><item switchcode="SILVER">SI=F</item><item switchcode="CRUDE OIL">CL=F</item><item switchcode="DOW JONES">^DJI</item><item switchcode="NASDAQ">^IXIC</item><item switchcode="GOLD">GC=F</item><item switchcode="S&amp;P500">^GSPC</item></group><group name="INDS"><item switchcode="HANG SENG">^HSI</item><item switchcode="CAC">^FCHI</item><item switchcode="TECDAX">^TECDAX</item><item switchcode="FTSE">^FTSE</item><item switchcode="NIKKEI">^N225</item><item switchcode="BITCOIN">BTC-USD</item><item switchcode="USD/JPY">JPY=X</item><item switchcode="GBP/USD">GBPUSD=X</item><item switchcode="EUR/USD">EURUSD=X</item><item switchcode="SILVER">SI=F</item><item switchcode="CRUDE OIL">CL=F</item><item switchcode="DOW JONES">^DJI</item><item switchcode="NASDAQ">^IXIC</item><item switchcode="GOLD">GC=F</item><item switchcode="S&amp;P500">^GSPC</item></group><group name="COMMONS"><item>NKE</item><item>GOOG</item><item>TSLA</item><item>MSFT</item></group><group name="FOREX"><item>USDEUR=X</item><item>BTC-USD=X</item><item>JPY=X</item><item>GBPUSD=X</item><item>EURUSD=X</item><item>ETH-USD</item><item>CHF=X</item><item>EURCHF=X</item><item>CHFJPY=X</item><item>AUD=X</item></group></list></settings><settings name="backtest"><setting name="increment" value="1" /></settings></config>
